name: skyphaa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0

#--------------- PACKAGES ---------------#
dependencies:
  flutter:
    sdk: flutter


  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  convex_bottom_bar: ^3.0.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  google_maps_flutter: ^2.2.2
  #  google_maps_flutter: ^2.7.0
  #  camera: ^0.11.0+1
  #  speech_to_text: ^6.6.2
  #  googleapis_auth: ^1.6.0
  #  flutter_tts: ^4.0.2
  #  googleapis: ^13.1.0
  #  font_awesome_flutter: ^10.7.0
  #  google_sign_in: ^6.2.1
  #  firebase_auth: ^5.1.2
  #  firebase_core: ^3.2.0
  #  provider: ^6.1.2

  win32: ^5.4.0
  js: ^0.6.5
  js_wrapping: ^0.7.3
  carousel_slider: ^5.0.0





  # Icons
  iconsax_flutter: ^1.0.0
  cupertino_icons: ^1.0.6

  #  State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  #  product Specific
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1


  # Firebase
  firebase_core: ^2.23.0



#--------------- ./ PACKAGES END ---------------#


dev_dependencies:
  flutter_test:
    sdk: flutter


  #--------------- ./ App icon ---------------#
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/Yellow Modern Gadget Store Logo (2).png"

  flutter_lints: ^4.0.0



flutter:


  uses-material-design: true

  #--------------- LOCAL ASSETS ---------------#
  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/icons/
    - assets/images/animations/
    - assets/icons/category_icons/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/brand/
    - assets/images/user/
    - assets/images/reviews/
    - assets/icons/payment_methods/
    - assets/images/
    - assets/fonts/

  #--------------- LOCAL FONTS ---------------#
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/static/Mulish-Black.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/static/Mulish-BoldItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/static/Mulish-Bold.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/static/Mulish-ExtraLight.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/static/Mulish-Italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/static/Mulish-Light.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/static/Mulish-Regular.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/static/Mulish-SemiBold.ttf
          weight: 900
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
