// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5MAH3n88ZPM5EkPWqPGE8lUFdPvgiYeI',
    appId: '1:703163262209:web:dc63d2e41f0398f9642700',
    messagingSenderId: '703163262209',
    projectId: 'skypha-ba9b7',
    authDomain: 'skypha-ba9b7.firebaseapp.com',
    storageBucket: 'skypha-ba9b7.appspot.com',
    measurementId: 'G-ZZ4KY2YGRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3-vLe31E6KPHVmO0p8tfGiaOmEky299I',
    appId: '1:703163262209:android:b2b605f3be3d1654642700',
    messagingSenderId: '703163262209',
    projectId: 'skypha-ba9b7',
    storageBucket: 'skypha-ba9b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeUR9XR_-meJXT5eWXHxSoHwZKbydHd50',
    appId: '1:703163262209:ios:3298fdf3f8ce53fd642700',
    messagingSenderId: '703163262209',
    projectId: 'skypha-ba9b7',
    storageBucket: 'skypha-ba9b7.appspot.com',
    androidClientId: '703163262209-dvbghi3t2urdluo0ac39gj8ao53pnl57.apps.googleusercontent.com',
    iosClientId: '703163262209-mvjif812p5t4vmcuai4a0aepb143s2po.apps.googleusercontent.com',
    iosBundleId: 'com.example.skypha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeUR9XR_-meJXT5eWXHxSoHwZKbydHd50',
    appId: '1:703163262209:ios:3298fdf3f8ce53fd642700',
    messagingSenderId: '703163262209',
    projectId: 'skypha-ba9b7',
    storageBucket: 'skypha-ba9b7.appspot.com',
    androidClientId: '703163262209-dvbghi3t2urdluo0ac39gj8ao53pnl57.apps.googleusercontent.com',
    iosClientId: '703163262209-mvjif812p5t4vmcuai4a0aepb143s2po.apps.googleusercontent.com',
    iosBundleId: 'com.example.skypha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5MAH3n88ZPM5EkPWqPGE8lUFdPvgiYeI',
    appId: '1:703163262209:web:8f0a1d4b568b9371642700',
    messagingSenderId: '703163262209',
    projectId: 'skypha-ba9b7',
    authDomain: 'skypha-ba9b7.firebaseapp.com',
    storageBucket: 'skypha-ba9b7.appspot.com',
    measurementId: 'G-544T0KYLKD',
  );

}